title: "FastAPI プロジェクトにすぐに活用できるテンプレート"
summary: "Pythonの人気バックエンドフレームワークのFastAPIを使った現場のプロジェクトにすぐに活用できる、超実用的なテンプレートの紹介です。"
topics: ["FastAPI", "Python", "バックエンド"]
published: true
price: 0 # 有料の場合200〜5000
# 本に含めるチャプターを順番に並べましょう
chapters:
  - introduction

